"""默认迁移模板。"""

"""stage2_models_9_11"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

revision = '94f73bae3568'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('after_sale_cases',
    sa.Column('id', sa.String(length=36), nullable=False, comment='申请单号'),
    sa.Column('order_id', sa.String(length=36), nullable=False, comment='订单ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('type', sa.String(length=32), nullable=False, comment='类型：RETURN/REFUND/AFTER_SALE_SERVICE'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态：SUBMITTED/UNDER_REVIEW/DECIDED/CLOSED'),
    sa.Column('amount', sa.Float(), nullable=False, comment='金额'),
    sa.Column('reason', sa.String(length=512), nullable=True, comment='原因'),
    sa.Column('evidence_urls', mysql.JSON(), nullable=True, comment='举证URL列表'),
    sa.Column('decided_by', sa.String(length=36), nullable=True, comment='裁决人（adminId）'),
    sa.Column('decision', sa.String(length=16), nullable=True, comment='裁决：APPROVE/REJECT'),
    sa.Column('decision_notes', sa.String(length=1024), nullable=True, comment='裁决备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_after_sale_cases_order_id'), 'after_sale_cases', ['order_id'], unique=False)
    op.create_index(op.f('ix_after_sale_cases_user_id'), 'after_sale_cases', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False, comment='审计ID'),
    sa.Column('actor_type', sa.String(length=32), nullable=False, comment='操作者类型'),
    sa.Column('actor_id', sa.String(length=36), nullable=False, comment='操作者ID'),
    sa.Column('action', sa.String(length=32), nullable=False, comment='动作'),
    sa.Column('resource_type', sa.String(length=64), nullable=False, comment='资源类型'),
    sa.Column('resource_id', sa.String(length=36), nullable=True, comment='资源ID'),
    sa.Column('summary', sa.String(length=512), nullable=True, comment='摘要'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='IP'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='UserAgent'),
    sa.Column('metadata', mysql.JSON(), nullable=True, comment='元数据（禁止存敏感明文）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False, comment='预约ID'),
    sa.Column('entitlement_id', sa.String(length=36), nullable=False, comment='权益ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('venue_id', sa.String(length=36), nullable=False, comment='场所ID'),
    sa.Column('service_type', sa.String(length=64), nullable=False, comment='服务类目标识'),
    sa.Column('booking_date', sa.Date(), nullable=False, comment='预约日期'),
    sa.Column('time_slot', sa.String(length=16), nullable=False, comment='时段：HH:mm-HH:mm'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：PENDING/CONFIRMED/CANCELLED/COMPLETED'),
    sa.Column('confirmation_method', sa.String(length=16), nullable=False, comment='确认方式：AUTO/MANUAL'),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True, comment='确认时间'),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True, comment='取消时间'),
    sa.Column('cancel_reason', sa.String(length=512), nullable=True, comment='取消原因'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_date'), 'bookings', ['booking_date'], unique=False)
    op.create_index(op.f('ix_bookings_entitlement_id'), 'bookings', ['entitlement_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookings_venue_id'), 'bookings', ['venue_id'], unique=False)
    op.create_table('cms_channels',
    sa.Column('id', sa.String(length=36), nullable=False, comment='栏目ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='栏目名称'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：ENABLED/DISABLED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_contents',
    sa.Column('id', sa.String(length=36), nullable=False, comment='内容ID'),
    sa.Column('channel_id', sa.String(length=36), nullable=False, comment='栏目ID'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='标题'),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True, comment='封面图'),
    sa.Column('summary', sa.String(length=512), nullable=True, comment='摘要'),
    sa.Column('content_html', sa.Text(), nullable=False, comment='正文（HTML）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：DRAFT/PUBLISHED/OFFLINE'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('effective_from', sa.DateTime(), nullable=True, comment='生效开始'),
    sa.Column('effective_until', sa.DateTime(), nullable=True, comment='生效结束'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_contents_channel_id'), 'cms_contents', ['channel_id'], unique=False)
    op.create_table('dealer_hierarchies',
    sa.Column('id', sa.String(length=36), nullable=False, comment='关系ID'),
    sa.Column('ancestor_dealer_id', sa.String(length=36), nullable=False, comment='祖先经销商ID'),
    sa.Column('descendant_dealer_id', sa.String(length=36), nullable=False, comment='后代经销商ID'),
    sa.Column('depth', sa.Integer(), nullable=False, comment='深度'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_hierarchies_ancestor_dealer_id'), 'dealer_hierarchies', ['ancestor_dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_hierarchies_descendant_dealer_id'), 'dealer_hierarchies', ['descendant_dealer_id'], unique=False)
    op.create_table('dealer_links',
    sa.Column('id', sa.String(length=36), nullable=False, comment='链接ID'),
    sa.Column('dealer_id', sa.String(length=36), nullable=False, comment='归属经销商ID'),
    sa.Column('product_id', sa.String(length=36), nullable=False, comment='高端服务卡商品ID'),
    sa.Column('campaign', sa.String(length=128), nullable=True, comment='活动/批次'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：ENABLED/DISABLED/EXPIRED'),
    sa.Column('valid_from', sa.DateTime(), nullable=True, comment='生效时间'),
    sa.Column('valid_until', sa.DateTime(), nullable=True, comment='到期时间'),
    sa.Column('url', sa.String(length=2048), nullable=False, comment='投放URL（示例/模板）'),
    sa.Column('uv', sa.Integer(), nullable=True, comment='访问UV（可为空）'),
    sa.Column('paid_count', sa.Integer(), nullable=True, comment='支付数（可为空）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_links_dealer_id'), 'dealer_links', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_links_product_id'), 'dealer_links', ['product_id'], unique=False)
    op.create_table('dealers',
    sa.Column('id', sa.String(length=36), nullable=False, comment='经销商ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='经销商名称'),
    sa.Column('level', sa.String(length=64), nullable=True, comment='层级标识'),
    sa.Column('parent_dealer_id', sa.String(length=36), nullable=True, comment='上级经销商ID'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：ACTIVE/SUSPENDED'),
    sa.Column('contact_name', sa.String(length=64), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=64), nullable=True, comment='联系电话'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealers_parent_dealer_id'), 'dealers', ['parent_dealer_id'], unique=False)
    op.create_table('enterprises',
    sa.Column('id', sa.String(length=36), nullable=False, comment='企业ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='企业名称'),
    sa.Column('country_code', sa.String(length=32), nullable=True, comment='国家编码（如 COUNTRY:CN）'),
    sa.Column('province_code', sa.String(length=32), nullable=True, comment='省编码（如 PROVINCE:110000）'),
    sa.Column('city_code', sa.String(length=32), nullable=True, comment='市编码（如 CITY:110100）'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='录入来源（用户首次绑定/导入/手工）'),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False, comment='首次出现时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprises_name'), 'enterprises', ['name'], unique=False)
    op.create_table('entitlement_transfers',
    sa.Column('id', sa.String(length=36), nullable=False, comment='转赠记录ID'),
    sa.Column('entitlement_id', sa.String(length=36), nullable=False, comment='权益ID'),
    sa.Column('from_owner_id', sa.String(length=36), nullable=False, comment='转出方 ownerId'),
    sa.Column('to_owner_id', sa.String(length=36), nullable=False, comment='转入方 ownerId'),
    sa.Column('transferred_at', sa.DateTime(), nullable=False, comment='转赠时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entitlement_transfers_entitlement_id'), 'entitlement_transfers', ['entitlement_id'], unique=False)
    op.create_index(op.f('ix_entitlement_transfers_from_owner_id'), 'entitlement_transfers', ['from_owner_id'], unique=False)
    op.create_index(op.f('ix_entitlement_transfers_to_owner_id'), 'entitlement_transfers', ['to_owner_id'], unique=False)
    op.create_table('entitlements',
    sa.Column('id', sa.String(length=36), nullable=False, comment='权益ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID（与 ownerId 一致）'),
    sa.Column('order_id', sa.String(length=36), nullable=False, comment='订单ID'),
    sa.Column('entitlement_type', sa.String(length=32), nullable=False, comment='类型：VOUCHER/SERVICE_PACKAGE'),
    sa.Column('service_type', sa.String(length=64), nullable=False, comment='服务类目标识'),
    sa.Column('remaining_count', sa.Integer(), nullable=False, comment='剩余次数'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='总次数'),
    sa.Column('valid_from', sa.DateTime(), nullable=False, comment='生效时间'),
    sa.Column('valid_until', sa.DateTime(), nullable=False, comment='到期时间'),
    sa.Column('applicable_venues', mysql.JSON(), nullable=True, comment='适用场所'),
    sa.Column('applicable_regions', mysql.JSON(), nullable=True, comment='适用区域'),
    sa.Column('qr_code', sa.String(length=2048), nullable=False, comment='二维码payload'),
    sa.Column('voucher_code', sa.String(length=128), nullable=False, comment='券码'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：ACTIVE/USED/EXPIRED/TRANSFERRED'),
    sa.Column('service_package_instance_id', sa.String(length=36), nullable=True, comment='服务包实例ID（仅 entitlementType=SERVICE_PACKAGE）'),
    sa.Column('owner_id', sa.String(length=36), nullable=False, comment='当前持有者（唯一裁决字段）'),
    sa.Column('activator_id', sa.String(length=36), nullable=False, comment='激活者'),
    sa.Column('current_user_id', sa.String(length=36), nullable=False, comment='当前使用者'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entitlements_order_id'), 'entitlements', ['order_id'], unique=False)
    op.create_index(op.f('ix_entitlements_owner_id'), 'entitlements', ['owner_id'], unique=False)
    op.create_index(op.f('ix_entitlements_service_package_instance_id'), 'entitlements', ['service_package_instance_id'], unique=False)
    op.create_index(op.f('ix_entitlements_user_id'), 'entitlements', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False, comment='通知ID'),
    sa.Column('receiver_type', sa.String(length=32), nullable=False, comment='接收者类型'),
    sa.Column('receiver_id', sa.String(length=36), nullable=False, comment='接收者ID'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：UNREAD/READ'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='已读时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_receiver_id'), 'notifications', ['receiver_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False, comment='订单ID（v1：展示字段 orderNo=id）'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('order_type', sa.String(length=32), nullable=False, comment='订单类型：PRODUCT/VIRTUAL_VOUCHER/SERVICE_PACKAGE'),
    sa.Column('total_amount', sa.Float(), nullable=False, comment='订单总金额'),
    sa.Column('payment_method', sa.String(length=32), nullable=False, comment='支付方式：WECHAT/ALIPAY/BANK_TRANSFER'),
    sa.Column('payment_status', sa.String(length=16), nullable=False, comment='支付状态：PENDING/PAID/FAILED/REFUNDED'),
    sa.Column('dealer_id', sa.String(length=36), nullable=True, comment='经销商归属'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('paid_at', sa.DateTime(), nullable=True, comment='支付时间'),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True, comment='银行转账确认时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_dealer_id'), 'orders', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False, comment='支付记录ID'),
    sa.Column('order_id', sa.String(length=36), nullable=False, comment='订单ID'),
    sa.Column('payment_method', sa.String(length=32), nullable=False, comment='支付方式：WECHAT/ALIPAY/BANK_TRANSFER'),
    sa.Column('payment_status', sa.String(length=16), nullable=False, comment='支付状态：PENDING/PAID/FAILED/REFUNDED'),
    sa.Column('amount', sa.Float(), nullable=False, comment='支付金额'),
    sa.Column('provider_payload', mysql.JSON(), nullable=True, comment='渠道原始返回'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.String(length=36), nullable=False, comment='分类ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='分类名称'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父级ID'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：ENABLED/DISABLED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_parent_id'), 'product_categories', ['parent_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False, comment='商品ID'),
    sa.Column('provider_id', sa.String(length=36), nullable=False, comment='服务提供方ID'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='标题'),
    sa.Column('fulfillment_type', sa.String(length=32), nullable=False, comment='履约类型：VIRTUAL_VOUCHER/SERVICE'),
    sa.Column('category_id', sa.String(length=36), nullable=True, comment='分类ID'),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True, comment='封面图'),
    sa.Column('image_urls', mysql.JSON(), nullable=True, comment='图片列表'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述（富文本/文本）'),
    sa.Column('price', mysql.JSON(), nullable=False, comment='价格对象'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='标签'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态：PENDING_REVIEW/ON_SALE/OFF_SHELF/REJECTED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_provider_id'), 'products', ['provider_id'], unique=False)
    op.create_table('redemption_records',
    sa.Column('id', sa.String(length=36), nullable=False, comment='核销记录ID'),
    sa.Column('entitlement_id', sa.String(length=36), nullable=False, comment='权益ID'),
    sa.Column('booking_id', sa.String(length=36), nullable=True, comment='预约ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('venue_id', sa.String(length=36), nullable=False, comment='场所ID'),
    sa.Column('service_type', sa.String(length=64), nullable=False, comment='服务类目标识'),
    sa.Column('redemption_method', sa.String(length=16), nullable=False, comment='方式：QR_CODE/VOUCHER_CODE'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：SUCCESS/FAILED'),
    sa.Column('failure_reason', sa.String(length=512), nullable=True, comment='失败原因'),
    sa.Column('operator_id', sa.String(length=36), nullable=False, comment='操作人ID'),
    sa.Column('redemption_time', sa.DateTime(), nullable=False, comment='核销时间'),
    sa.Column('service_completed_at', sa.DateTime(), nullable=True, comment='服务完成时间'),
    sa.Column('notes', sa.String(length=1024), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemption_records_booking_id'), 'redemption_records', ['booking_id'], unique=False)
    op.create_index(op.f('ix_redemption_records_entitlement_id'), 'redemption_records', ['entitlement_id'], unique=False)
    op.create_index(op.f('ix_redemption_records_user_id'), 'redemption_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_redemption_records_venue_id'), 'redemption_records', ['venue_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.String(length=36), nullable=False, comment='退款ID'),
    sa.Column('order_id', sa.String(length=36), nullable=False, comment='订单ID'),
    sa.Column('amount', sa.Float(), nullable=False, comment='退款金额'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：REQUESTED/APPROVED/REJECTED/PROCESSING/SUCCESS/FAILED'),
    sa.Column('reason', sa.String(length=512), nullable=True, comment='原因'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_table('service_package_instances',
    sa.Column('id', sa.String(length=36), nullable=False, comment='卡实例ID'),
    sa.Column('order_id', sa.String(length=36), nullable=False, comment='订单ID'),
    sa.Column('order_item_id', sa.String(length=36), nullable=False, comment='订单明细ID'),
    sa.Column('service_package_template_id', sa.String(length=36), nullable=False, comment='服务包模板ID（service_packages）'),
    sa.Column('owner_id', sa.String(length=36), nullable=False, comment='当前持有者（裁决字段一致）'),
    sa.Column('region_scope', sa.String(length=32), nullable=False, comment='区域范围（见区域编码口径）'),
    sa.Column('tier', sa.String(length=64), nullable=False, comment='等级/阶梯'),
    sa.Column('valid_from', sa.DateTime(), nullable=False, comment='生效时间'),
    sa.Column('valid_until', sa.DateTime(), nullable=False, comment='到期时间'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：ACTIVE/EXPIRED/TRANSFERRED/REFUNDED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_package_instances_order_id'), 'service_package_instances', ['order_id'], unique=False)
    op.create_index(op.f('ix_service_package_instances_order_item_id'), 'service_package_instances', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_service_package_instances_owner_id'), 'service_package_instances', ['owner_id'], unique=False)
    op.create_index(op.f('ix_service_package_instances_service_package_template_id'), 'service_package_instances', ['service_package_template_id'], unique=False)
    op.create_table('service_packages',
    sa.Column('id', sa.String(length=36), nullable=False, comment='服务包模板ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='名称'),
    sa.Column('region_level', sa.String(length=16), nullable=False, comment='区域级别'),
    sa.Column('tier', sa.String(length=64), nullable=False, comment='等级'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement_records',
    sa.Column('id', sa.String(length=36), nullable=False, comment='结算单号'),
    sa.Column('dealer_id', sa.String(length=36), nullable=False, comment='经销商ID'),
    sa.Column('cycle', sa.String(length=32), nullable=False, comment='结算周期标识'),
    sa.Column('order_count', sa.Integer(), nullable=False, comment='订单数'),
    sa.Column('amount', sa.Float(), nullable=False, comment='应结算金额'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态：PENDING_CONFIRM/SETTLED/FROZEN'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('settled_at', sa.DateTime(), nullable=True, comment='结算完成时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_records_cycle'), 'settlement_records', ['cycle'], unique=False)
    op.create_index(op.f('ix_settlement_records_dealer_id'), 'settlement_records', ['dealer_id'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.String(length=36), nullable=False, comment='配置ID'),
    sa.Column('key', sa.String(length=128), nullable=False, comment='配置Key（全局唯一）'),
    sa.Column('value_json', mysql.JSON(), nullable=False, comment='配置值（JSON）'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='说明'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：ENABLED/DISABLED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('taxonomy_nodes',
    sa.Column('id', sa.String(length=36), nullable=False, comment='节点ID'),
    sa.Column('type', sa.String(length=16), nullable=False, comment='类型：VENUE/PRODUCT/CONTENT'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='名称'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父级ID'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：ENABLED/DISABLED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomy_nodes_parent_id'), 'taxonomy_nodes', ['parent_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('unionid', sa.String(length=64), nullable=True, comment='微信 unionid'),
    sa.Column('nickname', sa.String(length=64), nullable=False, comment='昵称'),
    sa.Column('avatar', sa.String(length=512), nullable=True, comment='头像'),
    sa.Column('identities', mysql.JSON(), nullable=False, comment='身份数组'),
    sa.Column('enterprise_id', sa.String(length=36), nullable=True, comment='企业ID'),
    sa.Column('enterprise_name', sa.String(length=128), nullable=True, comment='企业名称（冗余快照）'),
    sa.Column('binding_time', sa.DateTime(), nullable=True, comment='绑定生效时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_unionid'), 'users', ['unionid'], unique=False)
    op.create_table('venue_schedules',
    sa.Column('id', sa.String(length=36), nullable=False, comment='排期ID'),
    sa.Column('venue_id', sa.String(length=36), nullable=False, comment='场所ID'),
    sa.Column('service_type', sa.String(length=64), nullable=False, comment='服务类目标识'),
    sa.Column('booking_date', sa.Date(), nullable=False, comment='预约日期'),
    sa.Column('time_slot', sa.String(length=16), nullable=False, comment='时段：HH:mm-HH:mm'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='总容量'),
    sa.Column('remaining_capacity', sa.Integer(), nullable=False, comment='剩余容量'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：ENABLED/DISABLED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_schedules_booking_date'), 'venue_schedules', ['booking_date'], unique=False)
    op.create_index(op.f('ix_venue_schedules_service_type'), 'venue_schedules', ['service_type'], unique=False)
    op.create_index(op.f('ix_venue_schedules_venue_id'), 'venue_schedules', ['venue_id'], unique=False)
    op.create_table('venue_services',
    sa.Column('id', sa.String(length=36), nullable=False, comment='场所服务ID'),
    sa.Column('venue_id', sa.String(length=36), nullable=False, comment='场所ID'),
    sa.Column('service_type', sa.String(length=64), nullable=False, comment='服务类目标识'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='展示标题'),
    sa.Column('fulfillment_type', sa.String(length=32), nullable=False, comment='履约类型：VIRTUAL_VOUCHER/SERVICE'),
    sa.Column('product_id', sa.String(length=36), nullable=True, comment='关联商品ID'),
    sa.Column('booking_required', sa.Boolean(), nullable=False, comment='是否需要预约'),
    sa.Column('redemption_method', sa.String(length=16), nullable=False, comment='核销方式：QR_CODE/VOUCHER_CODE'),
    sa.Column('applicable_regions', mysql.JSON(), nullable=True, comment='适用区域标签'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：ENABLED/DISABLED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_services_product_id'), 'venue_services', ['product_id'], unique=False)
    op.create_index(op.f('ix_venue_services_service_type'), 'venue_services', ['service_type'], unique=False)
    op.create_index(op.f('ix_venue_services_venue_id'), 'venue_services', ['venue_id'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.String(length=36), nullable=False, comment='场所ID'),
    sa.Column('provider_id', sa.String(length=36), nullable=False, comment='服务提供方ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='场所名称'),
    sa.Column('logo_url', sa.String(length=512), nullable=True, comment='LOGO'),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True, comment='封面图'),
    sa.Column('image_urls', mysql.JSON(), nullable=True, comment='图片列表'),
    sa.Column('description', sa.Text(), nullable=True, comment='简介'),
    sa.Column('country_code', sa.String(length=32), nullable=True, comment='国家编码'),
    sa.Column('province_code', sa.String(length=32), nullable=True, comment='省编码'),
    sa.Column('city_code', sa.String(length=32), nullable=True, comment='市编码'),
    sa.Column('address', sa.String(length=512), nullable=True, comment='地址'),
    sa.Column('lat', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('lng', sa.Float(), nullable=True, comment='经度'),
    sa.Column('contact_phone', sa.String(length=64), nullable=True, comment='联系电话'),
    sa.Column('business_hours', sa.String(length=256), nullable=True, comment='营业时间'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='标签'),
    sa.Column('publish_status', sa.String(length=16), nullable=False, comment='发布状态：DRAFT/PUBLISHED/OFFLINE'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_city_code'), 'venues', ['city_code'], unique=False)
    op.create_index(op.f('ix_venues_country_code'), 'venues', ['country_code'], unique=False)
    op.create_index(op.f('ix_venues_provider_id'), 'venues', ['provider_id'], unique=False)
    op.create_index(op.f('ix_venues_province_code'), 'venues', ['province_code'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False, comment='明细ID'),
    sa.Column('order_id', sa.String(length=36), nullable=False, comment='订单ID'),
    sa.Column('item_type', sa.String(length=32), nullable=False, comment='明细类型：PRODUCT/VIRTUAL_VOUCHER/SERVICE_PACKAGE'),
    sa.Column('item_id', sa.String(length=36), nullable=False, comment='业务对象ID'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='标题'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='单价'),
    sa.Column('total_price', sa.Float(), nullable=False, comment='总价'),
    sa.Column('service_package_template_id', sa.String(length=36), nullable=True, comment='服务包模板ID（service_packages）'),
    sa.Column('region_scope', sa.String(length=32), nullable=True, comment='区域范围（见区域编码口径）'),
    sa.Column('tier', sa.String(length=64), nullable=True, comment='等级/阶梯'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_item_id'), 'order_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('package_services',
    sa.Column('id', sa.String(length=36), nullable=False, comment='明细ID'),
    sa.Column('service_package_id', sa.String(length=36), nullable=False, comment='服务包模板ID'),
    sa.Column('service_type', sa.String(length=64), nullable=False, comment='服务类目标识'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='次数'),
    sa.ForeignKeyConstraint(['service_package_id'], ['service_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_services_service_package_id'), 'package_services', ['service_package_id'], unique=False)
    op.create_table('user_enterprise_bindings',
    sa.Column('id', sa.String(length=36), nullable=False, comment='绑定ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False, comment='企业ID'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：PENDING/APPROVED/REJECTED'),
    sa.Column('binding_time', sa.DateTime(), nullable=False, comment='绑定时间（提交时间）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_enterprise_bindings_enterprise_id'), 'user_enterprise_bindings', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_user_enterprise_bindings_user_id'), 'user_enterprise_bindings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_enterprise_bindings_user_id'), table_name='user_enterprise_bindings')
    op.drop_index(op.f('ix_user_enterprise_bindings_enterprise_id'), table_name='user_enterprise_bindings')
    op.drop_table('user_enterprise_bindings')
    op.drop_index(op.f('ix_package_services_service_package_id'), table_name='package_services')
    op.drop_table('package_services')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_item_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_venues_province_code'), table_name='venues')
    op.drop_index(op.f('ix_venues_provider_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_country_code'), table_name='venues')
    op.drop_index(op.f('ix_venues_city_code'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_venue_services_venue_id'), table_name='venue_services')
    op.drop_index(op.f('ix_venue_services_service_type'), table_name='venue_services')
    op.drop_index(op.f('ix_venue_services_product_id'), table_name='venue_services')
    op.drop_table('venue_services')
    op.drop_index(op.f('ix_venue_schedules_venue_id'), table_name='venue_schedules')
    op.drop_index(op.f('ix_venue_schedules_service_type'), table_name='venue_schedules')
    op.drop_index(op.f('ix_venue_schedules_booking_date'), table_name='venue_schedules')
    op.drop_table('venue_schedules')
    op.drop_index(op.f('ix_users_unionid'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_taxonomy_nodes_parent_id'), table_name='taxonomy_nodes')
    op.drop_table('taxonomy_nodes')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_settlement_records_dealer_id'), table_name='settlement_records')
    op.drop_index(op.f('ix_settlement_records_cycle'), table_name='settlement_records')
    op.drop_table('settlement_records')
    op.drop_table('service_packages')
    op.drop_index(op.f('ix_service_package_instances_service_package_template_id'), table_name='service_package_instances')
    op.drop_index(op.f('ix_service_package_instances_owner_id'), table_name='service_package_instances')
    op.drop_index(op.f('ix_service_package_instances_order_item_id'), table_name='service_package_instances')
    op.drop_index(op.f('ix_service_package_instances_order_id'), table_name='service_package_instances')
    op.drop_table('service_package_instances')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_redemption_records_venue_id'), table_name='redemption_records')
    op.drop_index(op.f('ix_redemption_records_user_id'), table_name='redemption_records')
    op.drop_index(op.f('ix_redemption_records_entitlement_id'), table_name='redemption_records')
    op.drop_index(op.f('ix_redemption_records_booking_id'), table_name='redemption_records')
    op.drop_table('redemption_records')
    op.drop_index(op.f('ix_products_provider_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_product_categories_parent_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_dealer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_notifications_receiver_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_entitlements_user_id'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_service_package_instance_id'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_owner_id'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_order_id'), table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index(op.f('ix_entitlement_transfers_to_owner_id'), table_name='entitlement_transfers')
    op.drop_index(op.f('ix_entitlement_transfers_from_owner_id'), table_name='entitlement_transfers')
    op.drop_index(op.f('ix_entitlement_transfers_entitlement_id'), table_name='entitlement_transfers')
    op.drop_table('entitlement_transfers')
    op.drop_index(op.f('ix_enterprises_name'), table_name='enterprises')
    op.drop_table('enterprises')
    op.drop_index(op.f('ix_dealers_parent_dealer_id'), table_name='dealers')
    op.drop_table('dealers')
    op.drop_index(op.f('ix_dealer_links_product_id'), table_name='dealer_links')
    op.drop_index(op.f('ix_dealer_links_dealer_id'), table_name='dealer_links')
    op.drop_table('dealer_links')
    op.drop_index(op.f('ix_dealer_hierarchies_descendant_dealer_id'), table_name='dealer_hierarchies')
    op.drop_index(op.f('ix_dealer_hierarchies_ancestor_dealer_id'), table_name='dealer_hierarchies')
    op.drop_table('dealer_hierarchies')
    op.drop_index(op.f('ix_cms_contents_channel_id'), table_name='cms_contents')
    op.drop_table('cms_contents')
    op.drop_table('cms_channels')
    op.drop_index(op.f('ix_bookings_venue_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_entitlement_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_date'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_after_sale_cases_user_id'), table_name='after_sale_cases')
    op.drop_index(op.f('ix_after_sale_cases_order_id'), table_name='after_sale_cases')
    op.drop_table('after_sale_cases')
    # ### end Alembic commands ###
